[package]
name = "cmp"
version = "0.1.0"
license = "MIT/Apache-2.0"
authors = ["est31 <MTest31@outlook.com>"]

[dependencies]
lewton = { path = "../../" }
vorbis = { git = "https://github.com/Luni-4/vorbis-rs" }
test-assets = "0.2"
